// Expanded college list with top NIRF and QS ranked institutions in India
// The app will show these options in the dropdown. If the user's college is not listed
// they can select "Other" and type their institution name in the text input.
export const COLLEGES = [
  "BML Munjal University",
  
  // IITs (Indian Institutes of Technology)
  "Indian Institute of Technology Bombay",
  "Indian Institute of Technology Delhi",
  "Indian Institute of Technology Madras",
  "Indian Institute of Technology Kanpur",
  "Indian Institute of Technology Kharagpur",
  "Indian Institute of Technology Roorkee",
  "Indian Institute of Technology Guwahati",
  "Indian Institute of Technology Hyderabad",
  "Indian Institute of Technology Indore",
  "Indian Institute of Technology (BHU) Varanasi",
  "Indian Institute of Technology Gandhinagar",
  "Indian Institute of Technology Ropar",
  "Indian Institute of Technology Bhubaneswar",
  "Indian Institute of Technology Jodhpur",
  "Indian Institute of Technology Patna",
  "Indian Institute of Technology Mandi",
  "Indian Institute of Technology (ISM) Dhanbad",
  "Indian Institute of Technology Tirupati",
  "Indian Institute of Technology Palakkad",
  "Indian Institute of Technology Jammu",
  "Indian Institute of Technology Goa",
  "Indian Institute of Technology Bhilai",
  "Indian Institute of Technology Dharwad",
  
  // NITs (National Institutes of Technology)
  "National Institute of Technology Tiruchirappalli",
  "National Institute of Technology Rourkela",
  "National Institute of Technology Karnataka, Surathkal",
  "National Institute of Technology Warangal",
  "National Institute of Technology Calicut",
  "National Institute of Technology Durgapur",
  "National Institute of Technology Silchar",
  "National Institute of Technology Hamirpur",
  "National Institute of Technology Jaipur",
  "National Institute of Technology Kurukshetra",
  "National Institute of Technology Raipur",
  "National Institute of Technology Agartala",
  "National Institute of Technology Allahabad",
  "National Institute of Technology Bhopal",
  "National Institute of Technology Jalandhar",
  "National Institute of Technology Jamshedpur",
  "National Institute of Technology Manipur",
  "National Institute of Technology Meghalaya",
  "National Institute of Technology Mizoram",
  "National Institute of Technology Nagaland",
  "National Institute of Technology Patna",
  "National Institute of Technology Puducherry",
  "National Institute of Technology Sikkim",
  "National Institute of Technology Srinagar",
  "National Institute of Technology Uttarakhand",
  "National Institute of Technology Goa",
  "National Institute of Technology Andhra Pradesh",
  "National Institute of Technology Delhi",
  
  // IISERs (Indian Institutes of Science Education and Research)
  "Indian Institute of Science, Bangalore",
  "Indian Institute of Science Education and Research Pune",
  "Indian Institute of Science Education and Research Kolkata",
  "Indian Institute of Science Education and Research Mohali",
  "Indian Institute of Science Education and Research Thiruvananthapuram",
  "Indian Institute of Science Education and Research Bhopal",
  "Indian Institute of Science Education and Research Tirupati",
  
  // IIMs (Indian Institutes of Management)
  "Indian Institute of Management Ahmedabad",
  "Indian Institute of Management Bangalore",
  "Indian Institute of Management Calcutta",
  "Indian Institute of Management Lucknow",
  "Indian Institute of Management Kozhikode",
  "Indian Institute of Management Indore",
  "Indian Institute of Management Shillong",
  "Indian Institute of Management Rohtak",
  "Indian Institute of Management Ranchi",
  "Indian Institute of Management Raipur",
  "Indian Institute of Management Tiruchirappalli",
  "Indian Institute of Management Udaipur",
  "Indian Institute of Management Kashipur",
  "Indian Institute of Management Nagpur",
  "Indian Institute of Management Visakhapatnam",
  "Indian Institute of Management Amritsar",
  "Indian Institute of Management Bodh Gaya",
  "Indian Institute of Management Sambalpur",
  "Indian Institute of Management Sirmaur",
  "Indian Institute of Management Jammu",
  
  // Central Universities
  "University of Delhi",
  "Jawaharlal Nehru University",
  "Banaras Hindu University",
  "Aligarh Muslim University",
  "University of Hyderabad",
  "Jamia Millia Islamia",
  "Tezpur University",
  "Pondicherry University",
  "North-Eastern Hill University",
  "University of Allahabad",
  "Visva-Bharati University",
  
  // Deemed Universities
  "Birla Institute of Technology and Science, Pilani",
  "Manipal Academy of Higher Education",
  "Amity University",
  "VIT University, Vellore",
  "SRM Institute of Science and Technology",
  "Thapar Institute of Engineering and Technology",
  "KIIT University",
  "Lovely Professional University",
  "Shiv Nadar University",
  "Kalinga Institute of Industrial Technology",
  "Bharati Vidyapeeth Deemed University",
  "Symbiosis International University",
  "JSS Academy of Higher Education and Research",
  "Saveetha Institute of Medical and Technical Sciences",
  "Chandigarh University",
  
  // State Universities
  "Anna University",
  "University of Calcutta",
  "University of Madras",
  "University of Mumbai",
  "University of Pune",
  "Osmania University",
  "Andhra University",
  "Acharya Nagarjuna University",
  "Sri Venkateswara University",
  "Kakatiya University",
  "University of Kerala",
  "Mahatma Gandhi University, Kerala",
  "Cochin University of Science and Technology",
  "Gujarat University",
  "M.S. University of Baroda",
  "Panjab University",
  "Guru Nanak Dev University",
  "Rajasthan University",
  "University of Rajasthan",
  "Utkal University",
  "Berhampur University",
  
  // Specialized Institutions
  "All India Institute of Medical Sciences, New Delhi",
  "Indian Statistical Institute",
  "Indian Institute of Foreign Trade",
  "National Law School of India University, Bangalore",
  "National Institute of Fashion Technology",
  "Indian Institute of Mass Communication",
  "Homi Bhabha National Institute",
  "Tata Institute of Fundamental Research",
  "Sree Chitra Tirunal Institute for Medical Sciences and Technology",
  "Post Graduate Institute of Medical Education and Research, Chandigarh",
  
  // Private Universities
  "Ashoka University",
  "O.P. Jindal Global University",
  "FLAME University",
  "Azim Premji University",
  "Presidency University, Bangalore",
  "Christ University",
  "Jain University",
  "NMIMS University",
  "Bennett University",
  "Graphic Era University",
  "Galgotias University",
  "Amrita Vishwa Vidyapeetham",
  "CMR University",
  "BML Munjal University",
  
  // Top Engineering Colleges
  "Delhi Technological University",
  "Netaji Subhas University of Technology",
  "Jadavpur University",
  "College of Engineering, Pune",
  "PSG College of Technology",
  "Thiagarajar College of Engineering",
  "Coimbatore Institute of Technology",
  "Government College of Technology, Coimbatore",
  "Veermata Jijabai Technological Institute",
  "Institute of Chemical Technology, Mumbai",
  "Motilal Nehru National Institute of Technology Allahabad",
  "BMS College of Engineering",
  "RV College of Engineering",
  "MS Ramaiah Institute of Technology",
  "PES University",
  "Birla Institute of Technology, Mesra",
  "National Institute of Technology Sikkim",
];
